### PR TITLE
Re-focus on search field when coming back to bookmark index page

### LINKED ISSUE #46: Re-focus after click
Hello,

Search field is auto-focused, which is perfect, we just have to type after having reached the Webmarks tab for the first time, and click on the link we want, which is then opened in a new tab. Perfect.
However, when we come back to the Webmarks tab, search field is not focused anymore, because we previously clicked on one of the links in the page.

Do you think it could be possible to automatically "re-focus" the search field ?

Thank you very much 👍 

Ben

### PR DESCRIPTION
**Pull request by galfert**
Closes #46 

This focuses the search field when coming back to the tab (while on the bookmarks index page) using the Page Visibility API.

### CODE REVIEW

**Comment by skddc** [comment]
The existing auto-focus is happening on the component itself. Is there a reason, this can't be added to the component as well? Also, the `activate` one is superfluous, as it's in additon to the component's own `didInsertElement` one, no?

**Comment by galfert** [comment]
Oh, I didn't see that there is a separate component for the search input. Will move the code into there.

**Comment by benrubson** [comment]
Hi,
Do you have some news regarding this PR ?
Many thanks 👍 
Ben

**Comment by galfert** [comment]
Oh, I kind of forgot about this one. So thanks for the reminder :)

I will try to get this ready sometime this week.

**Comment by galfert** [comment]
Moved the code responsible for re-focusing the field into the component itself.

Ready for review.

**Comment by benrubson** [comment]
Thank yo uvery much @galfert 👍

**Comment by skddc** [comment]
@galfert Thanks!

**Pull request merged**
