### PR TITLE
Upgrade Ember

### LINKED ISSUE #14: Error on changing tags in `bookmark/edit` and canceling
When you edit a bookmarks tags (e.g. add a space after the comma) and click "cancel" it throws a JS error and the app chokes on it.

### LINKED ISSUE #24: Upgrade to Ember CLI, Ember 2.0 etc.

### PR DESCRIPTION
**Pull request by galfert**
Closes #24
Fixes #14

It's almost all working as before again. I think the only thing missing is the recognition of the remoteStorage connection status. For that the two variables `rsConnecting` and `rsConnected` have to be moved from the global Ember App (`app/app.js`). Probably into some service object.

### CODE REVIEW

**Comment by galfert** [comment]
I think everything is working now.

Tests are also all green for me locally. So would be great if you could activate Travis for this repo now.

**Comment by skddc** [comment]
Great, thanks a lot!

I set up Circle CI for this repo now. It's a bit faster and more stable than Travis has been recently in my experience.

**Comment by skddc** [comment]
When I'm connecting my test account, I get two Ember objects for each RS object. Looks like it's receiving change events in addition to the `getAll` or something.

**Comment by galfert** [comment]
Damn, didn't notice that. Will try to find a fix for it.

**Comment by skddc** [comment]
Great, thanks! Let me know if I can help.

**Comment by galfert** [comment]
Issue should be fixed now.

**Comment by skddc** [comment]
This works, but it completely detaches loading bookmarks from the index route. That means that the loading animation isn't shown at all anymore, and there's no way to know when the route is loaded, because in theory it's loaded instantly, while data loading is seperate.

I think this is the wrong approach, and without the spinner, with a larger amount of bookmarks, it's not a nice UX anymore.

I think there shouldn't be any change events for new remote objects in the first place, while a `getAll` is running for the same directory. The old code didn't do anything special in that regard.

**Comment by skddc** [comment]
... another issue, apart from the route loading, is that some views shouldn't start loading all bookmarks. The bookmarklet for example should open the `/new` route immediately, and there's #25 for not redirecting to the list after creating one, so that UX for creating gets even better.

**Comment by galfert** [comment]
Ah, you are right. The bookmarks should be loaded from the model hook, so the loading action is triggered as expected.

I will look into that.

**Comment by galfert** [comment]
Changed the bookmark loading to only load all bookmarks when going to the index route, but not for the new or edit route. Now also the loading animation works again.

Also fixed some other issues I found, like the missing bookmarklet link and resetting the query params from the bookmarklet link when cancelling the form. Otherwise the form would still have prefilled fields when just going back to the new bookmark route.

I also added a mechanism that redirects you back to the route you attempted to access while remoteStorage wasn't in connected state yet, instead of just keeping you on the welcome route.

**Comment by skddc** [comment]
Looking *very* good! I think it's all working now, and actually quite a bit faster due to all the Ember improvements.

**Pull request merged**
